Update bash script to handle invalid inputs

diff --git a/services b/services
--- a/services
+++ b/services
@@ -9,14 +9,14 @@ set -e
 
 if (( $# != 1 )); then
 	echo "Illegal number of parameters"
-	echo "usage: services [start|stop]"
+	echo "usage: services [create|start|stop]"
 	exit 1
 fi
 
 command="$1"
 case "${command}" in
 	"help")
-		echo "usage: services [start|stop]"
+		echo "usage: services [create|start|stop]"
 		;;
 	"start")
 		echo -e "Starting two containers \033[1;34mOrion\033[0m and a \033[1;30mMongoDB\033[0m database."
@@ -33,4 +33,10 @@ case "${command}" in
 		docker pull mongo:3.6
 		echo "Obtaining Latest Orion Image"
 		docker pull fiware/orion
+		;;
+	*)
+		echo "Command not Found."
+		echo "usage: services [create|start|stop]"
+		exit 127;
+		;;
 esac
